### ISSUE TITLE
support for custom datasets

### ISSUE THREAD

**Issue by hosea7456** [prolearner/hypergrad#4]
Hi, thanks for your great job. I wonder if your work support for  custom datasets? 
I would like to train on open-datasets and then test on my own datasets.
Thank you!

**Comment by prolearner** [comment]
Hi, thanks for your interest. We do not plan to include additional dataset support here since we want to this project to be light (meaning only the core methods and examples of use). Feel free to adapt the examples to your needs. If you have any issue with that you can also contact me privately.
