### ISSUE TITLE
Modification for the feature-head setting of meta-learning?

### ISSUE THREAD

**Issue by XavierXiao** [prolearner/hypergrad#5]
Thanks for the excellent hyper-grad implementation! I read the iMAML example, but in MAML, the whole network is the meta-model, and in the feature-head setting, we have a common feature extractor as the meta-model, while a task-specific head as inner variables. What are the major modifications to the iMAML example for this scenario? 

In particular, how to pass the meta_model argument to the Task class? Should we still send the whole (feature+head) as meta_model, while specify params to be the parameter of head, and hparams to be the parameter of feature? A simple example pointing out what should be changed would be perfect. Thanks!

**Comment by prolearner** [comment]
Thanks for the interest in the code. In the "feature-head" setting the meta_model is only the feature network. Furthermore,  in this setting the inner optimizer should work directly on the features to avoid  the additional cost of computing them at each step in the inner loop. This could be achieved for example by passing the output of the feature network to the Task class constructor at each outer iteration. The Task class would use the features and a linear model to compute the losses (no need to use higher).

**Comment by XavierXiao** [comment]
Thanks! That is clear!
