### ISSUE TITLE
What does "stochastic" mean here?

### ISSUE THREAD

**Issue by SungFeng-Huang** [prolearner/hypergrad#6]
As titled, what does "stochastic" mean in hg.CG and hg.fix_point? Does this mean the inner loop can be updated with SGD?

https://github.com/prolearner/hypertorch/blob/24826349f73d84f0820da429023f6f6aeada7c74/hypergrad/hypergradients.py#L143

**Comment by prolearner** [comment]
Exactly. When `stochastic=True`, `fp_map` is called K times (if `fp_map` is SGD each call will give a different value depending on the mini-batch) while, when `stochastic=False` `fp_map` is called just 1 time to save computation. Autograd is always used K times for Jacobian-vector products.

**Comment by SungFeng-Huang** [comment]
Got it. Thanks!
